services:
  message_pipeline:
    build: .
    restart: always
    networks:
      - project_network
    
  postgres:
    image: postgres:10.5
    restart: always
    networks:
      - project_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  project_network:
    driver: bridge